{
 "title": "Order API Overview",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Order API - Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(lab_http_requests_total{\r\n    job=\"order-api\",\r\n    route=\"/orders\"\r\n  }[2m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order API - Server Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  rate(lab_http_requests_total{\r\n    job=\"order-api\",\r\n    route=\"/orders\",\r\n    status_code=~\"5..\"\r\n  }[2m])\r\n)\r\n/\r\nsum(\r\n  rate(lab_http_requests_total{\r\n    job=\"order-api\",\r\n    route=\"/orders\"\r\n  }[2m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order API - Average Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(lab_http_request_duration_seconds_sum{\r\n    job=\"order-api\",\r\n    route=\"/orders\"\r\n  }[2m])\r\n)\r\n/\r\nsum(\r\n  rate(lab_http_request_duration_seconds_count{\r\n    job=\"order-api\",\r\n    route=\"/orders\"\r\n  }[2m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Order API - P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(lab_http_request_duration_seconds_bucket{\r\n      job=\"order-api\",\r\n      route=\"/orders\"\r\n    }[2m])\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}